# Single dimsension NumPy Array

In [1]:
!dir

 Volume in drive D is data 
 Volume Serial Number is EA49-4141

 Directory of D:\GEN_AI\Data_Science\NumPy

11/27/2025  09:38 AM    <DIR>          .
11/27/2025  08:19 AM    <DIR>          ..
11/27/2025  09:30 AM    <DIR>          .ipynb_checkpoints
11/27/2025  09:38 AM            25,251 Classroom_NumPy.ipynb
11/27/2025  09:29 AM               168 my_name.npy
               2 File(s)         25,419 bytes
               3 Dir(s)  91,912,101,888 bytes free


In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np
n1 = np.array([10,20,30,40])
n1

array([10, 20, 30, 40])

In [4]:
import numpy as np
n2=np.array([
    [10,20,30],
    [10,80,90],
    [30,50,80]
])
n2

array([[10, 20, 30],
       [10, 80, 90],
       [30, 50, 80]])

In [5]:
n2.shape

(3, 3)

# initialize NumPy array with zeros

In [6]:
n3=np.zeros((11,11))

In [7]:
n3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

# initialization a array of matrix with full then

In [8]:
n4=np.full((11,11),9)
n4

array([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

# initialization of NumPy array within a range

In [9]:
n5=np.arange(10,19)
n5

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [10]:
n6=np.arange(10,19).reshape(3,3)
n6

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

# Initialization of NumPy array with the skip numbers

In [11]:
n7=np.arange(1,10,2)
n7

array([1, 3, 5, 7, 9])

# Initialize NumPy array with the random numbers

In [12]:
n8=np.random.randint(100000,1000000,50)
n8

array([604815, 547742, 795960, 429721, 606260, 907072, 217531, 361711,
       402185, 982685, 754538, 349777, 518832, 347092, 760968, 931826,
       526613, 882624, 924129, 818796, 892517, 797465, 407579, 462402,
       841673, 407376, 864884, 584436, 363964, 589291, 252529, 125082,
       685282, 605867, 756441, 462709, 154983, 852988, 879785, 429420,
       914519, 191691, 620568, 182898, 521042, 576041, 908308, 479394,
       762401, 513607], dtype=int32)

# Joining NumPy arrays

In [13]:
a = np.arange(1,11)
b = np.arange(1,21,2)
c = np.random.randint(1,100,10)
d = np.random.randint(1,30,10)
e = np.random.randint(1,50,10)
print(a,b,c,d,e)

[ 1  2  3  4  5  6  7  8  9 10] [ 1  3  5  7  9 11 13 15 17 19] [91 97 31 84 20 84 52 28 33 44] [16  8 21 25 24 18 12  4  4  5] [ 6 13 12 13 17 42 36 39 25 48]


In [14]:
np.vstack((a,b,c,d,e))

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19],
       [91, 97, 31, 84, 20, 84, 52, 28, 33, 44],
       [16,  8, 21, 25, 24, 18, 12,  4,  4,  5],
       [ 6, 13, 12, 13, 17, 42, 36, 39, 25, 48]])

In [15]:
np.column_stack((a,b,c,d,e))

array([[ 1,  1, 91, 16,  6],
       [ 2,  3, 97,  8, 13],
       [ 3,  5, 31, 21, 12],
       [ 4,  7, 84, 25, 13],
       [ 5,  9, 20, 24, 17],
       [ 6, 11, 84, 18, 42],
       [ 7, 13, 52, 12, 36],
       [ 8, 15, 28,  4, 39],
       [ 9, 17, 33,  4, 25],
       [10, 19, 44,  5, 48]])

In [16]:
np.hstack((a,b,c,d,e))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  1,  3,  5,  7,  9, 11, 13,
       15, 17, 19, 91, 97, 31, 84, 20, 84, 52, 28, 33, 44, 16,  8, 21, 25,
       24, 18, 12,  4,  4,  5,  6, 13, 12, 13, 17, 42, 36, 39, 25, 48])

# NumPy Intersection and Differences

In [17]:
x = np.array([10,20,30,40,50,60])
y = np.array([30,50,90,100,120,150])

In [18]:
np.intersect1d(x,y)

array([30, 50])

In [19]:
np.setdiff1d(x,y)

array([10, 20, 40, 60])

In [20]:
np.union1d(x,y)

array([ 10,  20,  30,  40,  50,  60,  90, 100, 120, 150])

# Addition of NumPy Arrays

In [21]:
t = np.array([10,20])
s = np.array([30,40])

In [22]:
np.sum([t,s])

np.int64(100)

In [23]:
np.sum([t,s],axis=0)

array([40, 60])

In [24]:
np.sum([t,s],axis=1)

array([30, 70])

# NumPy array mathematics

In [25]:
p = np.array([10,20,30])

In [26]:
p+1

array([11, 21, 31])

In [27]:
p = np.array([10,20,30])
p+p

array([20, 40, 60])

In [28]:
p = np.array([10,20,30])
p-p

array([0, 0, 0])

In [29]:
p = np.array([10,20,30])
p%3

array([1, 2, 0])

In [30]:
p = np.array([10,20,30])
p*p

array([100, 400, 900])

In [31]:
p = np.array([10,20,30])
p/p

array([1., 1., 1.])

In [32]:
p = np.array([10,20,30])
p/3

array([ 3.33333333,  6.66666667, 10.        ])

# NumPy Maths Function

In [33]:
nn = np.array([10,20,30,60])

In [34]:
nn = np.array([10,20,30,60])
np.mean(nn)   #Mean is sensitive to outliers

np.float64(30.0)

In [35]:
nn = np.array([10,20,30,60])
np.median(nn) #Median is used when there are outliers

np.float64(25.0)

In [36]:
nn = np.array([10,20,30,60])
np.std(nn)

np.float64(18.708286933869708)

In [37]:
nn = np.array([10,20,30,60])
np.quantile(nn,0.50)  #0.25=first quartile, 0.5=median, 0.75=3rd quartile

np.float64(25.0)

In [38]:
nn = np.array([10,20,30,60])
np.var(nn)

np.float64(350.0)

In [39]:
nn = np.array([10,20,30,60])
np.cov(nn)

array(466.66666667)

In [40]:
nn = np.array([10,20,30,60])
np.max(nn)

np.int64(60)

In [41]:
nn = np.array([10,20,30,60])
np.min(nn)

np.int64(10)

# Saving and Loading NumPy arrays

In [42]:
n11 = np.array([10,20,30,40,50])

In [43]:
np.save('my_name',n11)   #Saving the numpy array

In [44]:
np.load('my_name.npy')

array([10, 20, 30, 40, 50])

# Identity vs Eye

In [45]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [46]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

# Einstein  Summation Conventions

### Einsum
This fumction is used to compute many multi-dimensional and linear alebric operations on arrays

In [47]:
a = np.arange(1,10).reshape(3,3)
b = np.arange(21,30).reshape(3,3)
print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[21 22 23]
 [24 25 26]
 [27 28 29]]


In [48]:
#extract diagonals
np.einsum('ii->i',a)

array([1, 5, 9])

In [49]:
np.einsum('ii->i',b)

array([21, 25, 29])

In [50]:
#transpose
np.einsum('ij->ji',a)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [51]:
np.einsum('ij->ji',b)

array([[21, 24, 27],
       [22, 25, 28],
       [23, 26, 29]])

In [52]:
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [53]:
b.T

array([[21, 24, 27],
       [22, 25, 28],
       [23, 26, 29]])

In [55]:
#determinant
np.linalg.det(a)

np.float64(0.0)

In [59]:
np.linalg.inv(b)  #inverse

array([[ 1.40737488e+14, -2.81474977e+14,  1.40737488e+14],
       [-2.81474977e+14,  5.62949953e+14, -2.81474977e+14],
       [ 1.40737488e+14, -2.81474977e+14,  1.40737488e+14]])

In [58]:
#Matrix Multiplication
np.einsum('ij,jk',a,b)

array([[150, 156, 162],
       [366, 381, 396],
       [582, 606, 630]])

# Matrix and Vector Multiplication

In [60]:
A = np.array([[1,2], [3,4], [5,6]])
x = np.array([7,8])
print(np.einsum('ij,j->i', A, x))

[23 53 83]
